import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import ThemeProviderComponent from "@/app/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner"
import { PostHogProvider } from "./providers/PostHogProvider";


const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-roboto",
});
export const metadata: Metadata = {
	title: "Lynfera",
	description: "Generated by creation",
	icons: {
		icon: '/public/icon.svg',
	},

};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${roboto.className}  antialiased`} style={{ colorScheme: "dark" }}
			><PostHogProvider>
					<ReduxProvider>
						<ThemeProviderComponent>
							{children}
							<Toaster position="top-right" visibleToasts={5}
								richColors closeButton />
						</ThemeProviderComponent>
					</ReduxProvider>
				</PostHogProvider>
			</body>
		</html>
	);
}
